---
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

name: Release VSCode Extensions

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (e.g. v1.2.3)
        required: true
        default: 0.0.1

permissions: {}

jobs:
  discover:
    name: Discover extensions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Input version check
      run: |
        if ! [[ "$INPUT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(rc|alpha|beta)[0-9]+)?$ ]]; then
          echo "[ERROR]: Input version doesn't follow semver: $INPUT_VERSION"
          exit 1
        fi
      env:
        INPUT_VERSION: ${{ inputs.version }}
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Build extension matrix
      id: set-matrix
      run: |
        extensions=()
        for package in $(find . -name package.json -maxdepth 2 -mindepth 2 -type f | sort);do
          dir=$(dirname "$package" | sed 's,^\./,,')
          output=$( jq --indent 0 "{dir: \"$dir\", publisher: .publisher, name: .name, version: .version}" "$package")
          extensions+=($output)
        done
        matrix=$(printf '%s\n' "${extensions[@]}" | jq -sc '{"include": .}')
        echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  package:
    name: Package extension ${{ matrix.name }}
    needs: discover
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: actions/setup-node@v6
      with:
        cache-dependency-path: ${{ matrix.dir }}/package-lock.json

    - name: Install dependencies
      working-directory: ${{ matrix.dir }}
      run: npm ci --no-fund

    - name: Compile / build
      working-directory: ${{ matrix.dir }}
      run: npm run compile --if-present

    - name: Run tests
      working-directory: ${{ matrix.dir }}
      run: npm test --if-present

    - name: Package extension (.vsix)
      working-directory: ${{ matrix.dir }}
      run: |
        cp ../LICENSE .
        npm install --no-fund --global @vscode/vsce --prefer-offline
        vsce package --no-dependencies \
          --out "../$MATRIX_PUBLISHER.$MATRIX_NAME-$MATRIX_VERSION.vsix"
      env:
        MATRIX_PUBLISHER: ${{ matrix.publisher }}
        MATRIX_NAME: ${{ matrix.name }}
        MATRIX_VERSION: ${{ matrix.version }}

    - name: Upload artefact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.name }}-${{ matrix.version }}
        path: "*.vsix"
        retention-days: 1
        if-no-files-found: error
  publish:
    name: Publish GitHub Release
    needs: package
    runs-on: ubuntu-latest
    # environment: publish-gh
    permissions:
      contents: write
    steps:
    - name: Download all artefacts
      uses: actions/download-artifact@v7
      with:
        path: dist/

    - name: Create release & upload assets
      run: |
        gh release create "v$INPUT_VERSION" \
          --repo "${{ github.repository }}" \
          --title "Release $INPUT_VERSION" \
          --generate-notes \
          $(find dist -name "*.vsix" | tr '\n' ' ')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_VERSION: ${{ github.event.inputs.version }}
